openapi: 3.0.0
info:
  title: A minimal OpenAPI Description
  version: 0.1.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"
paths: 
  /book_details:
    $ref: "./path/book_details.yaml"
  /display_specific_book_detail/{bookId}:
    $ref: "./path/display_specific_book_detail.yaml"
  /student_details:
    $ref: "./path/student_details.yaml"
  /display_specific_student_detail/{rollNo}:
    $ref: "./path/display_specific_student_detail.yaml"
  /issue_book_details:
    $ref: "./path/issue_book_details.yaml"
  /return_book_details/{rollNo}/{bookId}:
    $ref: "./path/return_book_details.yaml"
